# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('fromName', models.CharField(max_length=100)),
                ('billTo', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=8)),
                ('paymentTerms', models.CharField(max_length=8)),
                ('dueDate', models.CharField(max_length=8)),
                ('balanceDue', models.CharField(max_length=10)),
                ('subTotal', models.CharField(max_length=10)),
                ('taxFlag', models.CharField(max_length=1)),
                ('tax', models.CharField(max_length=10)),
                ('discountFlag', models.CharField(max_length=1)),
                ('discount', models.CharField(max_length=10)),
                ('shipping', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('amountPaid', models.CharField(max_length=10)),
                ('toAddress', models.CharField(max_length=80)),
                ('toCity', models.CharField(max_length=80)),
                ('toState', models.CharField(max_length=2)),
                ('toZipcode', models.CharField(max_length=5)),
                ('toTel', models.CharField(max_length=10)),
                ('toFax', models.CharField(max_length=10)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('company', models.ManyToManyField(related_name='companyName', to='accounts.Account')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
