# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20171114_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='account_id',
            new_name='account',
        ),
    ]
