# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20171117_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discountFlag',
            field=models.CharField(choices=[('0', '%'), ('1', '$')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='taxFlag',
            field=models.CharField(choices=[('0', '%'), ('1', '$')], max_length=1),
        ),
    ]
