# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('tel', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
