# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.CharField(max_length=80),
        ),
    ]
