# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0003_auto_20171117_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.IntegerField()),
                ('quantity', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10)),
                ('ammount', models.CharField(max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='invoices.Invoice')),
            ],
        ),
    ]
