# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='ammount',
            new_name='amount',
        ),
    ]
