# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineitems', '0002_auto_20171117_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='line',
            name='description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='line',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='line',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
